colossus/apps/templates/urls.py
from django.urls import path

from . import views

app_name = 'templates'


urlpatterns = [
    path('', views.EmailTemplateListView.as_view(), name='emailtemplates'),
    path('add/', views.EmailTemplateCreateView.as_view(), name='emailtemplate_add'),
    path('<int:pk>/', views.email_template_editor, name='emailtemplate_editor'),
    path('<int:pk>/edit/', views.EmailTemplateUpdateView.as_view(), name='emailtemplate_edit'),
    path('<int:pk>/preview/', views.email_template_preview, name='emailtemplate_preview'),
    path('<int:pk>/autosave/', views.email_template_autosave, name='emailtemplate_autosave'),
    path('<int:pk>/delete/', views.EmailTemplateDeleteView.as_view(), name='emailtemplate_delete')
]

colossus/django_school/django_school/urls.py
from django.urls import include, path

from classroom.views import classroom, students, teachers

urlpatterns = [
    path('', include('classroom.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
]

colossus/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from colossus.apps.core import views as core_views
from colossus.apps.clientapp import views as client_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard1/', core_views.dashboard, name='dashboard'),
    path('send/testsms/', core_views.dashboard, name='test_sms'),
    path('send/bulksms/', client_views.send_bulk_sms, name='send_bulk'),
    path('', include('colossus.apps.subscribers.urls', namespace='subscribers')),
    path('', core_views.dashboard, name='dashboard'),
    path('dashboard/', core_views.dashboardnew, name='dashboardnew'),
    path('idmanagement/', core_views.SenderIdMmanagement, name='idmanagement'),
    path('sendquicksms/', core_views.sendquicksms, name='sendquicksms'),
    path('setup/', core_views.setup, name='setup'),
    path('setup/account/', core_views.setup_account, name='setup_account'),
    path('settings/', core_views.SiteUpdateView.as_view(), name='settings'),
    path('accounts/', include('colossus.apps.accounts.urls')),
    path('lists/', include('colossus.apps.lists.urls', namespace='lists')),
    path('notifications/', include('colossus.apps.notifications.urls', namespace='notifications')),
    path('templates/', include('colossus.apps.templates.urls', namespace='templates')),
    path('campaigns/', include('colossus.apps.campaigns.urls', namespace='campaigns')),
    path('<slug:mailing_list_slug>/', core_views.subscribe_shortcut, name='subscribe_shortcut'),
    path('<slug:mailing_list_slug>/unsubscribe/', core_views.unsubscribe_shortcut, name='unsubscribe_shortcut'),
]


if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

colossus/apps/templates/templates/templates/default_email_template_content.html
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
  <!--[if gte mso 15]><xml><o:OfficeDocumentSettings><o:AllowPNG/><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml><![endif]-->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ subject }}</title>
</head>
<body>
  {% block content %}{% endblock %}
  {% block footer %}
    <div><br></div>
    <div>
      <small><a href="{{ unsub }}">Unsubscribe from this list</a>.</small>
    </div>
  {% endblock %}
</body>
</html>

colossus/apps/templates/templates/templates/emailtemplate_confirm_delete.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans 'Delete' %}{% endblock %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'templates:emailtemplates' %}">{% trans 'Templates' %}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'templates:emailtemplate_editor' email_template.pk %}">{{ email_template.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{% trans 'Delete' %}</li>
    </ol>
  </nav>
  <div class="card mb-3">
    <div class="card-body">
      <h2 class="card-title">{% trans 'Are you sure?' %}</h2>
      <p>You are about to delete the template <strong>{{ email_template.name }}</strong>.</p>
      <form method="post" novalidate>
        {% csrf_token %}
        <button type="submit" class="btn btn-danger" role="button">{% trans 'Confirm deletion' %}</button>
        <a href="{% url 'templates:emailtemplate_editor' email_template.pk %}" class="btn btn-outline-secondary" role="button">{% trans 'Never mind' %}</a>
      </form>
    </div>
  </div>
{% endblock %}

colossus/apps/templates/templates/templates/emailtemplate_editor.html
{% extends 'base.html' %}

{% load crispy_forms_tags i18n static %}

{% block title %}{{ email_template.name }}{% endblock %}

{% block javascript %}
  <script src="{% static 'vendor/jquery.are-you-sure.js' %}"></script>
  <script src="{% static 'vendor/ace/1.3.3/ace.js' %}"></script>
  <script>
    $(function () {
      var editorHeight = $(window).height() - $("#editor").offset()['top'] - 18;
      $("#aceEditor").css("height", editorHeight + "px");
      $("#previewEmailContainer .card-body").css("height", editorHeight + "px");

      var editor = ace.edit("aceEditor");
      editor.setTheme("ace/theme/clouds");
      editor.getSession().setOptions({
        mode: "ace/mode/django",
        wrap: true,
        tabSize: 2,
        useSoftTabs: true
      });

      var $form = $("#templateForm");
      var updatePreview = false;
      var processingRequest = false;

      editor.on("change", function (e) {
        $("#id_content").val(editor.getValue());
        updatePreview = true;
      });

      setInterval(function () {
        if (updatePreview && !processingRequest) {
          $.ajax({
            url: $form.attr("data-preview-url"),
            type: $form.attr("method"),
            data: $form.serialize(),
            dataType: 'json',
            beforeSend: function () {
              processingRequest = true;
            },
            success: function (data) {
              $("#previewTemplate").contents().find("html").html(data.html);
            },
            error: function () {},
            complete: function () {
              updatePreview = false;
              processingRequest = false;
            }
          });
        }
      }, 2000);  // Every two seconds



      $form.submit(function () {
        $("#id_content").val(editor.getValue());
        return true;
      });

      $form.areYouSure({
        message: $form.attr("data-are-you-sure-message")
      });

    });
  </script>
{% endblock %}

{% block main %}
  <div class="container-fluid">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'templates:emailtemplates' %}">{% trans 'Templates' %}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ email_template.name }}</li>
      </ol>
    </nav>

    <form id="templateForm"
          method="post"
          novalidate
          data-preview-url="{% url 'templates:emailtemplate_preview' email_template.pk %}"
          data-are-you-sure-message="{% trans 'You have unsaved changes!' %}">
      {% csrf_token %}
      <div style="display:none!important">
        {{ form.content }}
      </div>
      <div class="mb-3 d-flex justify-content-between align-items-center">
        <div class="d-flex align-items-center">
          <h2 class="mb-0 mr-2">{{ email_template.name }}</h2>
          <a href="{% url 'templates:emailtemplate_edit' email_template.pk %}" class="btn btn-sm btn-link" role="button">{% trans 'Edit name' %}</a>
        </div>
        <div>
          <a href="{% url 'templates:emailtemplate_delete' email_template.pk %}" class="btn btn-outline-danger" role="button">{% trans 'Delete template' %}</a>
          <button type="submit" name="action" value="save_changes" class="btn btn-outline-success" role="button">{% trans 'Save changes' %}</button>
          <button type="submit" name="action" value="save_and_close" class="btn btn-success" role="button">{% trans 'Save and close' %}</button>
        </div>
      </div>

      {% if form.content.errors %}
        <div class="alert alert-danger">
          {% for error in form.content.errors %}
          <div>{{ error }}</div>
          {% endfor %}
        </div>
      {% endif %}

      <div class="row" id="editor">
        <div class="col-lg-6">
          <div class="card {% if form.errors %}border-danger{% else %}border-primary{% endif %} mb-3">
            <div class="card-body p-0">
              <div id="aceEditor" style="height:300px">{{ form.instance.content }}</div>
            </div>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="card" id="previewEmailContainer">
            <div class="card-body p-0">
              <iframe src="{% url 'templates:emailtemplate_preview' email_template.pk %}" id="previewTemplate" class="w-100 h-100" style="border:0;"></iframe>
            </div>
          </div>
        </div>
      </div>
    </form>

  </div>
{% endblock %}

colossus/apps/templates/templates/templates/emailtemplate_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags i18n %}

{% block title %}{% spaceless %}
  {% if email_template %}
    {% trans 'Edit template' %}
  {% else %}
    {% trans 'Create a new template' %}
  {% endif %}
{% endspaceless %}{% endblock %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'templates:emailtemplates' %}">{% trans 'Templates' %}</a></li>
      {% if email_template %}
        <li class="breadcrumb-item"><a href="{% url 'templates:emailtemplate_editor' email_template.pk %}">{{ email_template.name }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{% trans 'Edit template' %}</li>
      {% else %}
        <li class="breadcrumb-item active" aria-current="page">{% trans 'New template' %}</li>
      {% endif %}
    </ol>
  </nav>
  <div class="card">
    <div class="card-body">
      <h3 class="card-title">
        {% if email_template %}
          {% trans 'Edit template' %}
        {% else %}
          {% trans 'Create a new template' %}
        {% endif %}
      </h3>
      <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        {% if email_template %}
          <button type="submit" class="btn btn-success" role="button">{% trans 'Save changes' %}</button>
          <a href="{% url 'templates:emailtemplate_editor' email_template.pk %}" class="btn btn-outline-secondary" role="button">{% trans 'Never mind' %}</a>
        {% else %}
          <button type="submit" class="btn btn-success" role="button">{% trans 'Create template' %}</button>
          <a href="{% url 'templates:emailtemplates' %}" class="btn btn-outline-secondary" role="button">{% trans 'Never mind' %}</a>
        {% endif %}
      </form>
    </div>
  </div>
{% endblock %}

colossus/apps/templates/templates/templates/emailtemplate_list.html
{% extends 'base.html' %}

{% load colossus i18n %}

{% block title %}{% trans 'Templates' %}{% endblock %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">{% trans 'Templates' %}</li>
    </ol>
  </nav>
  <div class="card">
    <div class="card-body">
      <div class="d-flex justify-content-between align-items-center">
        <h2 class="mb-0">{% trans 'Templates' %}</h2>
        <a href="{% url 'templates:emailtemplate_add' %}" class="btn btn-primary" role="button">{% trans 'Create template' %}</a>
      </div>
    </div>
    <div class="list-group list-group-flush">
      <div class="list-group-item">
        <div class="row">
          <div class="col-6">
            <form method="get">
              <div class="input-group">
                <input type="text" name="q" value="{{ query }}" class="form-control" placeholder="{% trans 'Search templates' %}" aria-label="{% trans 'Search templates' %}">
                <div class="input-group-append">
                  {% if query %}
                    <a href="?" class="btn btn-outline-primary" role="button">
                      {% trans 'Clear' %}
                    </a>
                  {% endif %}
                  <button class="btn btn-primary" type="submit">{% trans 'Search' %}</button>
                </div>
              </div>
            </form>
          </div>
          <div class="col-6">
          </div>
        </div>
      </div>
    </div>
    <table class="table table-striped mb-0">
      <thead class="thead-light">
        <tr>
          <th>{% trans 'Name' %}</th>
          <th>{% trans 'Last update' %}</th>
          <th>{% trans 'Last used' %}</th>
        </tr>
      </thead>
      <tbody>
        {% for template in templates %}
          <tr>
            <td><a href="{{ template.get_absolute_url }}">{{ template.name }}</a></td>
            <td>{{ template.update_date }}</td>
            <td>{% spaceless %}
              {% if template.last_used_campaign %}
                By <a href="{{ template.last_used_campaign.get_absolute_url }}">{{ template.last_used_campaign.name }}</a> on
              {% endif %}
              {% if template.last_used_date %}
                {{ template.last_used_date }}
              {% else %}
                {% trans 'Never' %}
              {% endif %}
            {% endspaceless %}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% include 'includes/card_footer_paginator.html' %}
  </div>
{% endblock %}