colossus/apps/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('profile/', views.ProfileView.as_view(), name='profile'),
]

colossus/apps/campaigns/urls.py
from django.urls import path

from . import views

app_name = 'campaigns'

urlpatterns = [
    path('', views.CampaignListView.as_view(), name='campaigns'),
    path('add/', views.CampaignCreateView.as_view(), name='campaign_add'),
    path('<int:pk>/', views.CampaignDetailView.as_view(), name='campaign_detail'),
    path('<int:pk>/revert-draft/', views.CampaignRevertDraftView.as_view(), name='campaign_revert_draft'),
    path('<int:pk>/scheduled/', views.CampaignScheduledView.as_view(), name='campaign_scheduled'),
    path('<int:pk>/preview/', views.CampaignPreviewView.as_view(), name='campaign_preview'),
    path('<int:pk>/reports/', views.CampaignReportsView.as_view(), name='campaign_reports'),
    path('<int:pk>/reports/locations/', views.CampaignReportsLocationsView.as_view(),
         name='campaign_reports_locations'),
    path('<int:pk>/reports/locations/<str:country_code>/', views.CampaignReportsCountryView.as_view(),
         name='campaign_reports_country'),
    path('<int:pk>/links/', views.CampaignLinksView.as_view(), name='campaign_links'),
    path('<int:pk>/links/<int:link_pk>/edit/', views.LinkUpdateView.as_view(), name='edit_link'),
    path('<int:pk>/edit/', views.CampaignEditView.as_view(), name='campaign_edit'),
    path('<int:pk>/edit/name/', views.CampaignEditNameView.as_view(), name='campaign_edit_name'),
    path('<int:pk>/edit/recipients/', views.CampaignEditRecipientsView.as_view(), name='campaign_edit_recipients'),
    path('<int:pk>/edit/from/', views.CampaignEditFromView.as_view(), name='campaign_edit_from'),
    path('<int:pk>/edit/subject/', views.CampaignEditSubjectView.as_view(), name='campaign_edit_subject'),
    path('<int:pk>/edit/content/', views.campaign_edit_content, name='campaign_edit_content'),
    path('<int:pk>/edit/content/template/', views.CampaignEditTemplateView.as_view(), name='campaign_edit_template'),
    path('<int:pk>/edit/test-email/', views.campaign_test_email, name='campaign_test_email'),
    path('<int:pk>/preview-email/', views.campaign_preview_email, name='campaign_preview_email'),
    path('<int:pk>/send/', views.send_campaign, name='send_campaign'),
    path('<int:pk>/send/done/', views.SendCampaignCompleteView.as_view(), name='send_campaign_complete'),
    path('<int:pk>/replicate/', views.replicate_campaign, name='replicate_campaign'),
    path('<int:pk>/delete/', views.CampaignDeleteView.as_view(), name='delete_campaign'),
    path('<int:pk>/schedule/', views.ScheduleCampaignView.as_view(), name='schedule_campaign'),

    path('ajax/load-list-tags/', views.load_list_tags, name='load_list_tags'),
]

colossus/apps/lists/urls.py
# flake8: noqa

from django.urls import path

from . import views

app_name = 'mailing'


urlpatterns = [
    path('', views.MailingListListView.as_view(), name='lists'),
    path('add/', views.MailingListCreateView.as_view(), name='new_list'),
    path('<int:pk>/', views.MailingListDetailView.as_view(), name='list'),
    path('<int:pk>/locations/<str:country_code>/', views.MailingListCountryReportView.as_view(), name='country_report'),
    path('<int:pk>/subscribers/', views.SubscriberListView.as_view(), name='subscribers'),
    path('<int:pk>/subscribers/add/', views.SubscriberCreateView.as_view(), name='new_subscriber'),
    path('<int:pk>/subscribers/import/', views.ImportSubscribersView.as_view(), name='import_subscribers'),
    path('<int:pk>/subscribers/import/csv/', views.SubscriberImportView.as_view(), name='csv_import_subscribers'),
    path('<int:pk>/subscribers/import/csv/<int:import_pk>/', views.SubscriberImportPreviewView.as_view(), name='import_preview'),
    path('<int:pk>/subscribers/import/csv/<int:import_pk>/queued/', views.SubscriberImportQueuedView.as_view(), name='import_queued'),
    path('<int:pk>/subscribers/import/csv/<int:import_pk>/download/', views.download_subscriber_import, name='download_subscriber_import'),
    path('<int:pk>/subscribers/import/csv/<int:import_pk>/delete/', views.SubscriberImportDeleteView.as_view(), name='delete_subscriber_import'),
    path('<int:pk>/subscribers/import/paste/', views.PasteEmailsImportSubscribersView.as_view(), name='paste_import_subscribers'),
    path('<int:pk>/subscribers/<int:subscriber_pk>/', views.SubscriberDetailView.as_view(), name='subscriber'),
    path('<int:pk>/subscribers/<int:subscriber_pk>/edit/', views.SubscriberUpdateView.as_view(), name='edit_subscriber'),
    path('<int:pk>/subscribers/<int:subscriber_pk>/delete/', views.SubscriberDeleteView.as_view(), name='delete_subscriber'),

    path('<int:pk>/tags/', views.TagListView.as_view(), name='tags'),
    path('<int:pk>/tags/add/', views.TagCreateView.as_view(), name='new_tag'),
    path('<int:pk>/tags/bulk-tag/', views.BulkTagSubscribersView.as_view(), name='bulk_tag'),
    path('<int:pk>/tags/<int:tag_pk>/edit/', views.TagUpdateView.as_view(), name='edit_tag'),
    path('<int:pk>/tags/<int:tag_pk>/delete/', views.TagDeleteView.as_view(), name='delete_tag'),

    path('<int:pk>/forms/', views.SubscriptionFormsView.as_view(), name='subscription_forms'),
    path('<int:pk>/forms/editor/', views.FormsEditorView.as_view(), name='forms_editor'),
    path('<int:pk>/forms/editor/design/', views.CustomizeDesignView.as_view(), name='customize_design'),
    path('<int:pk>/forms/editor/<str:form_key>/', views.SubscriptionFormTemplateUpdateView.as_view(), name='edit_form_template'),
    path('<int:pk>/forms/editor/<str:form_key>/preview/', views.PreviewFormTemplateView.as_view(), name='preview_form_template'),
    path('<int:pk>/forms/editor/<str:form_key>/reset/', views.ResetFormTemplateView.as_view(), name='reset_form_template'),
    path('<int:pk>/settings/', views.ListSettingsView.as_view(), name='settings'),
    path('<int:pk>/settings/subscription/', views.SubscriptionSettingsView.as_view(), name='subscription_settings'),
    path('<int:pk>/settings/defaults/', views.CampaignDefaultsView.as_view(), name='defaults'),
    path('<int:pk>/settings/smtp/', views.SMTPCredentialsView.as_view(), name='smtp'),
    path('<int:pk>/charts/subscriptions/', views.SubscriptionsSummaryChartView.as_view(), name='charts_subscriptions_summary'),
    path('<int:pk>/charts/domains/', views.ListDomainsChartView.as_view(), name='charts_list_domains'),
    path('<int:pk>/charts/locations/', views.ListLocationsChartView.as_view(), name='charts_list_locations'),
]

colossus/apps/notifications/urls.py
from django.urls import path

from . import views

app_name = 'notifications'

urlpatterns = [
    path('', views.NotificationListView.as_view(), name='notifications'),
    path('<int:pk>/', views.NotificationDetailView.as_view(), name='notification_detail'),
    path('unread/', views.unread, name='unread'),
    path('mark-all-as-read/', views.mark_all_as_read, name='mark_all_as_read'),
    path('clear-all/', views.clear_all, name='clear_all'),
]

colossus/apps/templates/urls.py
from django.urls import path

from . import views

app_name = 'templates'


urlpatterns = [
    path('', views.EmailTemplateListView.as_view(), name='emailtemplates'),
    path('add/', views.EmailTemplateCreateView.as_view(), name='emailtemplate_add'),
    path('<int:pk>/', views.email_template_editor, name='emailtemplate_editor'),
    path('<int:pk>/edit/', views.EmailTemplateUpdateView.as_view(), name='emailtemplate_edit'),
    path('<int:pk>/preview/', views.email_template_preview, name='emailtemplate_preview'),
    path('<int:pk>/autosave/', views.email_template_autosave, name='emailtemplate_autosave'),
    path('<int:pk>/delete/', views.EmailTemplateDeleteView.as_view(), name='emailtemplate_delete')
]

colossus/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from colossus.apps.core import views as core_views
from colossus.apps.clientapp import views as client_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard1/', core_views.dashboard, name='dashboard'),
    path('send/testsms/', core_views.dashboard, name='test_sms'),
    path('send/bulksms/', client_views.send_bulk_sms, name='send_bulk'),
    path('', include('colossus.apps.subscribers.urls', namespace='subscribers')),
    path('', core_views.dashboard, name='dashboard'),
    path('dashboard/', core_views.dashboardnew, name='dashboardnew'),
    path('idmanagement/', core_views.SenderIdMmanagement, name='idmanagement'),
    path('sendquicksms/', core_views.sendquicksms, name='sendquicksms'),
    path('setup/', core_views.setup, name='setup'),
    path('setup/account/', core_views.setup_account, name='setup_account'),
    path('settings/', core_views.SiteUpdateView.as_view(), name='settings'),
    path('accounts/', include('colossus.apps.accounts.urls')),
    path('lists/', include('colossus.apps.lists.urls', namespace='lists')),
    path('notifications/', include('colossus.apps.notifications.urls', namespace='notifications')),
    path('templates/', include('colossus.apps.templates.urls', namespace='templates')),
    path('campaigns/', include('colossus.apps.campaigns.urls', namespace='campaigns')),
    path('<slug:mailing_list_slug>/', core_views.subscribe_shortcut, name='subscribe_shortcut'),
    path('<slug:mailing_list_slug>/unsubscribe/', core_views.unsubscribe_shortcut, name='unsubscribe_shortcut'),
]


if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

colossus/apps/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _

import pytz

from .models import User


class AdminUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email',)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_staff = True
        user.is_superuser = True
        if commit:
            user.save()
        return user


class UserForm(forms.ModelForm):
    TIMEZONE_CHOICES = (('', '---------'),) + tuple(map(lambda tz: (tz, tz), pytz.common_timezones))

    timezone = forms.ChoiceField(
        choices=TIMEZONE_CHOICES,
        required=False,
        label=_('Timezone')
    )

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'timezone')

colossus/apps/clientapp/forms.py
from django import forms

class SendMessageForm(forms.Form):
    title= forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    recepients = forms.CharField(widget=forms.Textarea)

colossus/apps/templates/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.template import Template, TemplateSyntaxError
from django.template.loader_tags import ExtendsNode, IncludeNode
from django.utils import timezone
from django.utils.translation import gettext

from .models import EmailTemplate


class EmailTemplateForm(forms.ModelForm):
    class Meta:
        model = EmailTemplate
        fields = ('content',)

    def clean_content(self):
        content = self.cleaned_data.get('content')

        try:
            template = Template(content)

            if template.nodelist.get_nodes_by_type(IncludeNode):
                include_tag_not_allowed = ValidationError(
                    gettext('Include blocks are not allowed.'),
                    code='include_tag_not_allowed'
                )
                self.add_error('content', include_tag_not_allowed)

            if template.nodelist.get_nodes_by_type(ExtendsNode):
                extends_tag_not_allowed = ValidationError(
                    gettext('Extends blocks are not allowed.'),
                    code='extends_tag_not_allowed'
                )
                self.add_error('content', extends_tag_not_allowed)

        except TemplateSyntaxError as tse:
            template_syntax_error = ValidationError(str(tse), code='template_syntax_error')
            self.add_error('content', template_syntax_error)

        return content

    def save(self, commit=True):
        email_template = super().save(commit=False)
        email_template.update_date = timezone.now()
        if commit:
            email_template.save()
        return email_template

colossus/apps/accounts/views.py
from django.conf import settings as django_settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import UpdateView
from django.contrib.auth import views as auth_views

from colossus.apps.accounts.forms import UserForm

from .models import User


class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserForm
    template_name = 'accounts/profile.html'
    success_url = reverse_lazy('profile')
    extra_context = {
        'local_css_urls' : django_settings.SB_ADMIN_CLIENT_CSS_LIBRARY_URLS,
        'local_js_urls' : django_settings.SB_ADMIN_CLIENT_JS_LIBRARY_URLS
            }


    def get_object(self, queryset=None):
        return self.request.user

colossus/apps/clientapp/views.py
from django.conf import settings as django_settings
from django.http import HttpResponseRedirect,HttpResponse
from django.shortcuts import render
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
import requests
import json
from .forms import SendMessageForm



def get_acess_token(request):
    url = "https://dsvc.safaricom.com:9480/api/auth/login"

    payload = {'username' :'TISA_API', 'password' : 'TISA_API@ps7331'}
    
    headers = {
        'Content-Type': 'application/json',
        'X-Requested-With': 'XMLHttpRequest'
    }

    response = requests.request("POST", url, headers=headers, data = json.dumps(payload))
    print(response.json())
    result=response.json()
    acess_token=result['token']
    print(acess_token)
    return acess_token
        
   


def send_bulk_sms(request):
    url = "https://dsvc.safaricom.com:9480/api/public/CMS/bulksms"
    access_token = get_acess_token(request)
    payload = "{\n\"timeStamp\": \"1556873649895\",\n\"dataSet\": [\n{\n\"userName\": \"tisa\",\n\"channel\": \"sms\",\n\"packageId\": \"5025\",\n\"oa\": \"JIHUSISHE\",\n\"msisdn\": \"254728826517,722877107\",\n\"message\": \"This is the bulk sms send\",\n\"uniqueId\": \"2500688298721\",\n\"actionResponseURL\": \"https://posthere.io/c59f-4786-86ac\"\n}\n]\n}"

    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = SendMessageForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            message = form.cleaned_data['message']
            recepients = form.cleaned_data['recepients']
         
           
        payload1={
        "timeStamp": "1556873649895",
        "dataSet": [
        {
        "userName": "tisa",
        "channel": "sms",
        "packageId": "5025",
        "oa": "jihusishe",
        "msisdn": recepients,
        "message": message,
        "uniqueId": "2500688298721",
        "actionResponseURL": "https://posthere.io/c59f-4786-86ac"
        }
        ]
        }
        headers = {
        'Content-Type': 'application/json',
        'X-Authorization': 'Bearer %s' % access_token}
        print(access_token)

        response = requests.request("POST", url, headers=headers,  data = json.dumps(payload1))
        result=response.json()
        print(result)
        # message=result["message"]
    
        return HttpResponse(message)
        
    else:
        form = SendMessageForm()

        return render(request, 'pages/sendbulk.html', 
        {
          'form': form,
          'local_css_urls' : django_settings.SB_ADMIN_CLIENT_CSS_LIBRARY_URLS,
          'local_js_urls' : django_settings.SB_ADMIN_CLIENT_JS_LIBRARY_URLS
   })


    
    
    
def send_ondemand_sms(request):
    access_token = get_acess_token(request)
    url = "https://dsvc.safaricom.com:9480/api/public/SDP/sendSMSRequest"

    payload = "{\n\"requestId\": 17,\n\"channel\": \"APIGW\",\n\"operation\": \"SendSMS\",\n\"requestParam\": {\n\"data\": [\n{\n\"name\": \"LinkId\",\n\"value\": \"\"\n},\n{\n\"name\": \"Msisdn\",\n\"value\": \"254728826517\"\n},\n{\n\"name\": \"Content\",\n\"value\": \"Thank You for Ondemand Subscription SAFRI TEST TUN Subscption test Send sms\"\n},\n{\n\"name\": \"OfferCode\",\n\"value\": \"001009700850\"\n},\n{\n\"name\": \"CpId\",\n\"value\": \"97\"\n}\n]\n}\n}"
    headers = {
    'Content-Type': 'application/json',
    'X-Requested-With': 'XMLHttpRequest',
    'X-Authorization': 'Bearer %s' % access_token
    }

    response = requests.request("POST", url, headers=headers, data = payload)

    print(response.text.encode('utf8'))

colossus/templates/base.html
{% load static i18n %}<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="theme-color" content="#ffffff">
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
  <link rel="mask-icon" href="{% static 'img/icon.svg' %}" color="#212529">
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap-4.2.1/css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/fontawesome-free-5.1.0-web/css/all.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Goudy+Bookletter+1911" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'notifications/css/notifications.css' %}">
  <title>{% block title %}Jihusishe{% endblock %}</title>
  {% block stylesheet %}
  {% endblock %}
</head>
<body>
{% block body %}
  <nav class="navbar navbar-expand-lg navbar-light py-3 mb-3 shadow-sm" style="background-color:#fff;">
    <a class="navbar-brand" href="{% url 'dashboard' %}">Jihusishe</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="mainMenu">
      <div class="navbar-nav mr-auto">
        <a class="nav-item nav-link{% if menu == 'dashboard' %} active{% endif %}" href="{% url 'dashboard' %}">
          {% trans 'Dashboard' %}
          {% if menu == 'dashboard' %}<span class="sr-only">{% trans '(current)' %}</span>{% endif %}
        </a>
        <a class="nav-item nav-link{% if menu == 'campaigns' %} active{% endif %}"
           href="{% url 'campaigns:campaigns' %}">
          {% trans 'Campaigns' %}
          {% if menu == 'campaigns' %}<span class="sr-only">{% trans '(current)' %}</span>{% endif %}
        </a>
        <a class="nav-item nav-link{% if menu == 'lists' %} active{% endif %}" href="{% url 'mailing:lists' %}">
          {% trans 'Sms Lists' %}
          {% if menu == 'lists' %}<span class="sr-only">{% trans '(current)' %}</span>{% endif %}
        </a>
        <a class="nav-item nav-link{% if menu == 'templates' %} active{% endif %}"
           href="{% url 'templates:emailtemplates' %}">
          {% trans 'Templates' %}
          {% if menu == 'templates' %}<span class="sr-only">{% trans '(current)' %}</span>{% endif %}
        </a>
      </div>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="javascript:void(0);"
             tabindex="0"
             class="nav-link"
             id="notifications"
             role="button"
             title="{% trans 'Notifications' %}"
             data-url="{% url 'notifications:unread' %}"
             data-loading="{% trans 'Loading notifications...' %}">
            <span class="has-notifications {% if notifications_count > 0 %} active{% endif %}">
              <span class="fa fa-bell text-primary"></span>
              <span class="badge badge-pill badge-danger px-1"
                    style="font-size:60%; position: absolute; margin-top: -25px; margin-left: 10px">{{ notifications_count }}</span>
            </span>
            <span class="empty-notifications {% if notifications_count == 0 %} active{% endif %}">
              <span class="far fa-bell"></span>
            </span>
            <span class="sr-only">{% trans 'Notifications' %}</span>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="userName" data-toggle="dropdown" aria-haspopup="true"
             aria-expanded="false">
            {{ user.username }}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userName">
            <a class="dropdown-item" href="{% url 'settings' %}">{% trans 'Account settings' %}</a>
            <a class="dropdown-item" href="{% url 'password_change' %}">{% trans 'Change password' %}</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}">{% trans 'Log out' %}</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>
  {% block main %}
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-10">
          {% include 'includes/messages.html' %}
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  {% endblock main %}
{% endblock body %}
<div id="notificationsContainer"></div>
<script src="{% static 'vendor/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'vendor/popper.js-1.14.6/umd/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap-4.2.1/js/bootstrap.min.js' %}"></script>
<script src="{% static 'notifications/js/notifications.js' %}"></script>
<script src="{% static 'vendor/feather-icons-4.7.3/feather.min.js' %}"></script>
<script src="{% static 'vendor/moment/moment.min.js' %}"></script>
<script src="{% static 'vendor/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<script>
  $(function () {
    feather.replace();
    $.fn.datetimepicker.Constructor.Default = $.extend({}, $.fn.datetimepicker.Constructor.Default, {
      icons: {
        time: 'far fa-clock',
        date: 'far fa-calendar',
        up: 'fa fa-arrow-up',
        down: 'fa fa-arrow-down',
        previous: 'fa fa-chevron-left',
        next: 'fa fa-chevron-right',
        today: 'far fa-calendar-check-o',
        clear: 'far fa-trash',
        close: 'far fa-times'
      }
    });
    $(".datetimeinput").datetimepicker({
      format: 'YYYY-MM-DD HH:mm:ss'
    });
  });
</script>
{% block javascript %}
{% endblock %}
</body>
</html>