colossus/apps/campaigns/urls.py
from django.urls import path

from . import views

app_name = 'campaigns'

urlpatterns = [
    path('', views.CampaignListView.as_view(), name='campaigns'),
    path('add/', views.CampaignCreateView.as_view(), name='campaign_add'),
    path('<int:pk>/', views.CampaignDetailView.as_view(), name='campaign_detail'),
    path('<int:pk>/revert-draft/', views.CampaignRevertDraftView.as_view(), name='campaign_revert_draft'),
    path('<int:pk>/scheduled/', views.CampaignScheduledView.as_view(), name='campaign_scheduled'),
    path('<int:pk>/preview/', views.CampaignPreviewView.as_view(), name='campaign_preview'),
    path('<int:pk>/reports/', views.CampaignReportsView.as_view(), name='campaign_reports'),
    path('<int:pk>/reports/locations/', views.CampaignReportsLocationsView.as_view(),
         name='campaign_reports_locations'),
    path('<int:pk>/reports/locations/<str:country_code>/', views.CampaignReportsCountryView.as_view(),
         name='campaign_reports_country'),
    path('<int:pk>/links/', views.CampaignLinksView.as_view(), name='campaign_links'),
    path('<int:pk>/links/<int:link_pk>/edit/', views.LinkUpdateView.as_view(), name='edit_link'),
    path('<int:pk>/edit/', views.CampaignEditView.as_view(), name='campaign_edit'),
    path('<int:pk>/edit/name/', views.CampaignEditNameView.as_view(), name='campaign_edit_name'),
    path('<int:pk>/edit/recipients/', views.CampaignEditRecipientsView.as_view(), name='campaign_edit_recipients'),
    path('<int:pk>/edit/from/', views.CampaignEditFromView.as_view(), name='campaign_edit_from'),
    path('<int:pk>/edit/subject/', views.CampaignEditSubjectView.as_view(), name='campaign_edit_subject'),
    path('<int:pk>/edit/content/', views.campaign_edit_content, name='campaign_edit_content'),
    path('<int:pk>/edit/content/template/', views.CampaignEditTemplateView.as_view(), name='campaign_edit_template'),
    path('<int:pk>/edit/test-email/', views.campaign_test_email, name='campaign_test_email'),
    path('<int:pk>/preview-email/', views.campaign_preview_email, name='campaign_preview_email'),
    path('<int:pk>/send/', views.send_campaign, name='send_campaign'),
    path('<int:pk>/send/done/', views.SendCampaignCompleteView.as_view(), name='send_campaign_complete'),
    path('<int:pk>/replicate/', views.replicate_campaign, name='replicate_campaign'),
    path('<int:pk>/delete/', views.CampaignDeleteView.as_view(), name='delete_campaign'),
    path('<int:pk>/schedule/', views.ScheduleCampaignView.as_view(), name='schedule_campaign'),

    path('ajax/load-list-tags/', views.load_list_tags, name='load_list_tags'),
]

colossus/apps/lists/urls.py
# flake8: noqa

from django.urls import path

from . import views

app_name = 'mailing'


urlpatterns = [
    path('', views.MailingListListView.as_view(), name='lists'),
    path('add/', views.MailingListCreateView.as_view(), name='new_list'),
    path('<int:pk>/', views.MailingListDetailView.as_view(), name='list'),
    path('<int:pk>/locations/<str:country_code>/', views.MailingListCountryReportView.as_view(), name='country_report'),
    path('<int:pk>/subscribers/', views.SubscriberListView.as_view(), name='subscribers'),
    path('<int:pk>/subscribers/add/', views.SubscriberCreateView.as_view(), name='new_subscriber'),
    path('<int:pk>/subscribers/import/', views.ImportSubscribersView.as_view(), name='import_subscribers'),
    path('<int:pk>/subscribers/import/csv/', views.SubscriberImportView.as_view(), name='csv_import_subscribers'),
    path('<int:pk>/subscribers/import/csv/<int:import_pk>/', views.SubscriberImportPreviewView.as_view(), name='import_preview'),
    path('<int:pk>/subscribers/import/csv/<int:import_pk>/queued/', views.SubscriberImportQueuedView.as_view(), name='import_queued'),
    path('<int:pk>/subscribers/import/csv/<int:import_pk>/download/', views.download_subscriber_import, name='download_subscriber_import'),
    path('<int:pk>/subscribers/import/csv/<int:import_pk>/delete/', views.SubscriberImportDeleteView.as_view(), name='delete_subscriber_import'),
    path('<int:pk>/subscribers/import/paste/', views.PasteEmailsImportSubscribersView.as_view(), name='paste_import_subscribers'),
    path('<int:pk>/subscribers/<int:subscriber_pk>/', views.SubscriberDetailView.as_view(), name='subscriber'),
    path('<int:pk>/subscribers/<int:subscriber_pk>/edit/', views.SubscriberUpdateView.as_view(), name='edit_subscriber'),
    path('<int:pk>/subscribers/<int:subscriber_pk>/delete/', views.SubscriberDeleteView.as_view(), name='delete_subscriber'),

    path('<int:pk>/tags/', views.TagListView.as_view(), name='tags'),
    path('<int:pk>/tags/add/', views.TagCreateView.as_view(), name='new_tag'),
    path('<int:pk>/tags/bulk-tag/', views.BulkTagSubscribersView.as_view(), name='bulk_tag'),
    path('<int:pk>/tags/<int:tag_pk>/edit/', views.TagUpdateView.as_view(), name='edit_tag'),
    path('<int:pk>/tags/<int:tag_pk>/delete/', views.TagDeleteView.as_view(), name='delete_tag'),

    path('<int:pk>/forms/', views.SubscriptionFormsView.as_view(), name='subscription_forms'),
    path('<int:pk>/forms/editor/', views.FormsEditorView.as_view(), name='forms_editor'),
    path('<int:pk>/forms/editor/design/', views.CustomizeDesignView.as_view(), name='customize_design'),
    path('<int:pk>/forms/editor/<str:form_key>/', views.SubscriptionFormTemplateUpdateView.as_view(), name='edit_form_template'),
    path('<int:pk>/forms/editor/<str:form_key>/preview/', views.PreviewFormTemplateView.as_view(), name='preview_form_template'),
    path('<int:pk>/forms/editor/<str:form_key>/reset/', views.ResetFormTemplateView.as_view(), name='reset_form_template'),
    path('<int:pk>/settings/', views.ListSettingsView.as_view(), name='settings'),
    path('<int:pk>/settings/subscription/', views.SubscriptionSettingsView.as_view(), name='subscription_settings'),
    path('<int:pk>/settings/defaults/', views.CampaignDefaultsView.as_view(), name='defaults'),
    path('<int:pk>/settings/smtp/', views.SMTPCredentialsView.as_view(), name='smtp'),
    path('<int:pk>/charts/subscriptions/', views.SubscriptionsSummaryChartView.as_view(), name='charts_subscriptions_summary'),
    path('<int:pk>/charts/domains/', views.ListDomainsChartView.as_view(), name='charts_list_domains'),
    path('<int:pk>/charts/locations/', views.ListLocationsChartView.as_view(), name='charts_list_locations'),
]

colossus/django_school/django_school/urls.py
from django.urls import include, path

from classroom.views import classroom, students, teachers

urlpatterns = [
    path('', include('classroom.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
]

colossus/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from colossus.apps.core import views as core_views
from colossus.apps.clientapp import views as client_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard1/', core_views.dashboard, name='dashboard'),
    path('send/testsms/', core_views.dashboard, name='test_sms'),
    path('send/bulksms/', client_views.send_bulk_sms, name='send_bulk'),
    path('', include('colossus.apps.subscribers.urls', namespace='subscribers')),
    path('', core_views.dashboard, name='dashboard'),
    path('dashboard/', core_views.dashboardnew, name='dashboardnew'),
    path('idmanagement/', core_views.SenderIdMmanagement, name='idmanagement'),
    path('sendquicksms/', core_views.sendquicksms, name='sendquicksms'),
    path('setup/', core_views.setup, name='setup'),
    path('setup/account/', core_views.setup_account, name='setup_account'),
    path('settings/', core_views.SiteUpdateView.as_view(), name='settings'),
    path('accounts/', include('colossus.apps.accounts.urls')),
    path('lists/', include('colossus.apps.lists.urls', namespace='lists')),
    path('notifications/', include('colossus.apps.notifications.urls', namespace='notifications')),
    path('templates/', include('colossus.apps.templates.urls', namespace='templates')),
    path('campaigns/', include('colossus.apps.campaigns.urls', namespace='campaigns')),
    path('<slug:mailing_list_slug>/', core_views.subscribe_shortcut, name='subscribe_shortcut'),
    path('<slug:mailing_list_slug>/unsubscribe/', core_views.unsubscribe_shortcut, name='unsubscribe_shortcut'),
]


if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

colossus/apps/core/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.crypto import get_random_string
from django.utils.translation import gettext_lazy as _


def default_token():
    return get_random_string(50)


class Token(models.Model):
    text = models.CharField(default=default_token, max_length=50, unique=True, editable=False)
    description = models.CharField(max_length=30, db_index=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_used = models.DateTimeField(null=True, blank=True)
    expires = models.IntegerField(default=7)
    content_type = models.ForeignKey(ContentType, on_delete=models.SET_NULL, null=True)
    object_id = models.PositiveIntegerField(null=True)
    content_object = GenericForeignKey()

    class Meta:
        verbose_name = _('token')
        verbose_name_plural = _('tokens')
        db_table = 'colossus_tokens'


class Option(models.Model):
    key = models.CharField(_('key'), max_length=50, unique=True)
    value = models.TextField(_('value'), blank=True)

    class Meta:
        verbose_name = _('option')
        verbose_name_plural = _('options')
        db_table = 'colossus_options'

    def __str__(self):
        if len(self.value) > 30:
            value = '%s...' % self.value[:30]
        else:
            value = self.value
        return '%s=%s' % (self.key, value)


class Country(models.Model):
    code = models.CharField(_('country code'), max_length=2, unique=True)
    name = models.CharField(_('name'), max_length=200)

    class Meta:
        verbose_name = _('country')
        verbose_name_plural = _('countries')
        db_table = 'colossus_countries'

    def __str__(self):
        return self.name


class City(models.Model):
    country = models.ForeignKey(
        Country,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name=_('country'),
        related_name='cities'
    )
    name = models.CharField(max_length=200)

    class Meta:
        verbose_name = _('city')
        verbose_name_plural = _('cities')
        db_table = 'colossus_cities'

    def __str__(self):
        return self.name

colossus/apps/core/views.py
from django.conf import settings as django_settings
from django.contrib import messages
from django.contrib.auth import get_user_model, login
from django.contrib.auth.decorators import login_required
from django.contrib.sites.models import Site
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.translation import gettext as _
from django.views.generic import UpdateView

from colossus.apps.accounts.forms import AdminUserCreationForm
from colossus.apps.campaigns.constants import CampaignStatus
from colossus.apps.campaigns.models import Campaign
from colossus.apps.lists.models import MailingList
from colossus.apps.subscribers.constants import ActivityTypes
from colossus.apps.subscribers.models import Activity

User = get_user_model()


@method_decorator(login_required, name='dispatch')
class SiteUpdateView(UpdateView):
    model = Site
    fields = ('name', 'domain',)
    template_name = 'core/site_form.html'
    success_url = reverse_lazy('settings')

    def get_object(self, queryset=None):
        return Site.objects.get(pk=django_settings.SITE_ID)


@login_required
def dashboardnew(request):
    campaigns = Campaign.objects.filter(status=CampaignStatus.DRAFT)
    activities = Activity.objects \
        .select_related('campaign', 'subscriber__mailing_list') \
        .filter(activity_type__in={ActivityTypes.SUBSCRIBED, ActivityTypes.UNSUBSCRIBED}) \
        .order_by('-date')[:50]
    return render(request, 'core/dashboard.html', {
        'menu': 'dashboard',
        'activities': activities,
        'drafts': campaigns
    })
# @login_required
# def dashboard(request):
#     campaigns = Campaign.objects.filter(status=CampaignStatus.DRAFT)
#     activities = Activity.objects \
#         .select_related('campaign', 'subscriber__mailing_list') \
#         .filter(activity_type__in={ActivityTypes.SUBSCRIBED, ActivityTypes.UNSUBSCRIBED}) \
#         .order_by('-date')[:50]
#     return render(request, 'pages/dashboard.html', {
#         'menu': 'dashboard',
#         'activities': activities,
#         'drafts': campaigns,
#         'local_css_urls' : django_settings.SB_ADMIN_CLIENT_CSS_LIBRARY_URLS,
#         'local_js_urls' : django_settings.SB_ADMIN_CLIENT_JS_LIBRARY_URLS
#     })

@login_required
def dashboard(request):
    campaigns = Campaign.objects.filter(status=CampaignStatus.DRAFT)
    activities = Activity.objects \
        .select_related('campaign', 'subscriber__mailing_list') \
        .filter(activity_type__in={ActivityTypes.SUBSCRIBED, ActivityTypes.UNSUBSCRIBED}) \
        .order_by('-date')[:50]
    return render(request, 'pages/dashboard.html', {
        'menu': 'dashboard',
        'activities': activities,
        'drafts': campaigns,
        'local_css_urls' : django_settings.SB_ADMIN_CLIENT_CSS_LIBRARY_URLS,
        'local_js_urls' : django_settings.SB_ADMIN_CLIENT_JS_LIBRARY_URLS
    })



def sendquicksms(request):
    return render(request, 'pages/sendquicksms.html', {
        'local_css_urls' : django_settings.SB_ADMIN_CLIENT_CSS_LIBRARY_URLS,
        'local_js_urls' : django_settings.SB_ADMIN_CLIENT_JS_LIBRARY_URLS
    })

def SenderIdMmanagement(request):
    return render(request, 'pages/idmanagement.html', {
        'local_css_urls' : django_settings.SB_ADMIN_CLIENT_CSS_LIBRARY_URLS,
        'local_js_urls' : django_settings.SB_ADMIN_CLIENT_JS_LIBRARY_URLS
    })

def setup(request):
    if User.objects.exists() or MailingList.objects.exists():
        return redirect('dashboard')

    site = Site.objects.get(pk=django_settings.SITE_ID)
    if site.domain == 'example.com':
        site.name = 'Colossus'
        site.domain = request.META.get('HTTP_HOST')
        site.save()
    return redirect('setup_account')


def setup_account(request):
    if User.objects.exists() or MailingList.objects.exists():
        return redirect('dashboard')

    if request.method == 'POST':
        form = AdminUserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, _('Account created with success! Go ahead and create your first mailing list.'))
            return redirect('lists:new_list')
    else:
        form = AdminUserCreationForm()
    return render(request, 'core/setup_account.html', {'form': form})


def subscribe_shortcut(request, mailing_list_slug):
    mailing_list = get_object_or_404(MailingList, slug=mailing_list_slug)
    return redirect('subscribers:subscribe', mailing_list_uuid=mailing_list.uuid)


def unsubscribe_shortcut(request, mailing_list_slug):
    mailing_list = get_object_or_404(MailingList, slug=mailing_list_slug)
    return redirect('subscribers:unsubscribe_manual', mailing_list_uuid=mailing_list.uuid)

colossus/apps/core/templates/core/dashboard.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h2 class="mb-0">{% trans 'Dashboard' %}</h2>
    <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
      <div class="dropdown">
        <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="draftsMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {% trans 'Drafts' %}
        </button>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="draftsMenu">
          {% for campaign in drafts %}
            <a class="dropdown-item" href="{{ campaign.get_absolute_url }}">{{ campaign.name }}</a>
          {% empty %}
            <div class="dropdown-item">
              <em class="text-muted">{% trans 'You have no draft.' %}</em>
            </div>
          {% endfor %}
        </div>
      </div>
      <a href="{% url 'campaigns:campaign_add' %}" class="btn btn-primary ml-2" role="button">{% trans 'Create campaign' %}</a>
    </div>
  </div>

  <h3>{% trans 'Activity' %}</h3>
  <hr class="mt-2">
  {% for activity in activities %}
    {% ifchanged %}
      <h6 class="mb-2 mt-4">{{ activity.date|date:'j M, Y' }}</h6>
    {% endifchanged %}
    <div class="card mb-2">
      <div class="card-body align-middle">
        {% if activity.is_subscribed %}
          <span class="fas fa-user-plus text-primary mr-2"></span>
          <small class="text-muted mr-2">{{ activity.date|date:'P' }}</small>
          <span>
            <a href="{% url 'lists:edit_subscriber' activity.subscriber.mailing_list_id activity.subscriber_id %}">
              {{ activity.subscriber.email }}
            </a>
            subscribed to
            <a href="{{ activity.subscriber.mailing_list.get_absolute_url }}">
              {{ activity.subscriber.mailing_list.name }}
            </a>
          </span>
        {% elif activity.is_unsubscribed %}
          <span class="fas fa-user-minus text-danger mr-2"></span>
          <small class="text-muted mr-2">{{ activity.date|date:'P' }}</small>
          <span>
            <a href="{% url 'lists:edit_subscriber' activity.subscriber.mailing_list_id activity.subscriber_id %}">
              {{ activity.subscriber.email }}
            </a>
            unsubscribed from
            <a href="{{ activity.subscriber.mailing_list.get_absolute_url }}">
              {{ activity.subscriber.mailing_list.name }}
            </a>
            {% if activity.campaign %}
              via <a href="{{ activity.campaign.get_absolute_url }}">{{ activity.campaign.name }}</a>
            {% endif %}
          </span>
        {% endif %}
      </div>
    </div>
  {% endfor %}


{% endblock %}

colossus/apps/core/templates/core/settings.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans 'Settings' %}{% endblock %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">{% trans 'Settings' %}</li>
    </ol>
  </nav>

  <div class="row">
    <div class="col-4">
      <div class="card mb-3">
        <div class="card-header">
          {% trans 'Personal settings' %}
        </div>
        <nav class="list-group list-group-flush">
          <a href="{% url 'profile' %}" class="list-group-item list-group-item-action">{% trans 'Profile' %}</a>
          <a href="{% url 'password_change' %}" class="list-group-item list-group-item-action">{% trans 'Change password' %}</a>
        </nav>
      </div>
      <div class="card mb-3">
        <div class="card-header">
          {% trans 'Application settings' %}
        </div>
        <nav class="list-group list-group-flush">
          <a href="{% url 'settings' %}" class="list-group-item list-group-item-action">{% trans 'Site domain' %}</a>
        </nav>
      </div>
    </div>
    <div class="col-8">
      <div class="card">
        <div class="card-body">
          {% block settingscontent %}
          {% endblock %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

colossus/apps/core/templates/core/setup.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans 'Initial Setup' %}{% endblock %}

{% block body %}
  <h1 class="logo text-center my-4">Jihusishe</h1>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <div class="card mb-3">
          <div class="card-body">
            <h4 class="card-title">{% trans 'Welcome to Jihusishe!' %}</h4>
            {% block content %}
            {% endblock %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

colossus/apps/core/templates/core/setup_account.html
{% extends 'core/setup.html' %}

{% load crispy_forms_tags i18n %}

{% block content %}
  <p class="lead">{% trans 'Create an admin account to manage Colossus:' %}</p>
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">{% trans 'Create admin account' %}</button>
  </form>
{% endblock %}

colossus/apps/core/templates/core/site_form.html
{% extends 'core/settings.html' %}

{% load crispy_forms_filters i18n %}

{% block settingscontent %}
  <h2 class="card-title">{% trans 'Site domain' %}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">{% trans 'Save changes' %}</button>
  </form>
{% endblock %}